newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 1

#
# Agent Configuration, describe your nginx instances here
#
agents:
  prodotti_agent:
    prodotti_host: "http://prodotti.shopa.com"
